# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-24.04
  tools:
    python: "3.13"
  jobs:
    install:
      - python -m pip install poetry
      - . "${READTHEDOCS_VIRTUALENV_PATH}/bin/activate" && python -m poetry install --with sphinx
