#!/bin/bash
set -ex

branch=$(git branch --show-current)

[[ $branch != main ]]

git push --all

git rebase --autostash main || git rebase --abort

# Ensure changelog is fed
[[ $(changelog current) != $(changelog suggest) ]]

git checkout main
git merge --no-ff "$branch"
git show-branch -a

read -p "Pressing enter will delete branch" && {
    git branch -D "$branch"
    git push --delete origin "$branch"
}
