#!/bin/bash

set -ex

[[ $(git branch --show-current) = main ]]

version=$(changelog suggest)
current=$(changelog current)

latest_tag=$(git describe --tags --abbrev=0)

# Safety check
[[ $latest_tag = $current ]]
# No changes ?
[[ $version != $latest_tag ]]

changelog release --yes

poetry version "$version"

sed -i "s/\(__version__ = \+\)\(.\).*/\1\2$version\2/" kaioretry/__init__.py
sed -i "s/\(release = \+\)\(.\).*/\1\2$version\2/" docs/source/conf.py

git commit -m "bump version to $version" \
    pyproject.toml CHANGELOG.md kaioretry/__init__.py docs/source/conf.py

git tag "$version"
git push
git push --tags
poetry build
poetry publish
