#!/bin/bash
# 

set -ex

[[ $# -eq 1 ]] || return

version=$1

poetry version "$version"

sed -i "s/\(__version__ = \+\)\(.\).*/\1\2$version\2/" kaioretry/__init__.py
sed -i "s/\(release = \+\)\(.\).*/\1\2$version\2/" docs/source/conf.py

date=$(date +%Y-%m-%d)

sed -i "s/## \[Unreleased\]/&\n\n## [$version] - $date/" CHANGELOG.md

git commit -m "bump version to $version" \
    pyproject.toml CHANGELOG.md kaioretry/__init__.py

git tag "$version"
git push
git push --tags
poetry build
poetry publish
